[params]
  [params.sectionMapping]
    "100.Teek" = "/teek/"
    "11.运维" = "/linux/"
    "20.前端" = "/frontend/"
    "30.编程" = "/code/"
    "35.黑客" = "/hacker/"
    "40.专题" = "/topic/"
    "50.工具" = "/tools/"
    "60.生活" = "/life/"
    "70.精神小屋" = "/love/"
    "80.娱乐" = "/entertainment/"
    "85.兴趣" = "/hobby/"
    "90.关于" = "/about/"
