[analytics]
  [analytics.busuanzi]
    api = "https://busuanzi-eo.xxdevops.cn/api/count"
    enabled = true
    page_pv = true
    pjax = false
    prefix = "busuanzi"
    site_pv = true
    site_uv = true
    style = "comma"
    type = "eo"
    url = "https://busuanzi-eo.xxdevops.cn/busuanzi.eo.js"
  [analytics.umami]
    enabled = true
    url = "https://umami.xxdevops.cn"
    websiteId = "a50c01fa-f866-488d-a328-3ac73aa639f7"

[comment]
  enabled = true
  envId = "https://twikoo.xxdevops.cn/"
  hideAdmin = false
  provider = "twikoo"
  version = "1.6.41"

[footer]
  [footer.analytics]
    la_widget_enabled = true
    la_widget_id = "3LmZHLhDZIDpMaT0"
    la_widget_theme = "#1690FF,#333333,#999999,#007BFF,#FFFFFF,#1690FF,12"
