[[main]]
name = '首页'
url = '/#home'
weight = 1

[[main]]
name = '技能'
url = '/#skills'
weight = 2

[[main]]
name = '文档'
url = '/#docs'
weight = 3

[[main]]
name = '项目'
url = '/#projects'
weight = 4

[[main]]
name = '关于'
url = '/#about'
weight = 5
