[params]
[params.author]
avatar = 'https://img.xxdevops.cn/blog/avatar/yuwen_avatar.avif?w=300&h=300&fit=crop&fm=webp&q=80'
email = ''
link = 'https://xxdevops.cn'
motto = '荆棘之路，劈风斩浪。'
name = '全溪小筑のBlog'
role = '设计师、产品经理、独立开发者、博主'
